/*
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.nem.sdk.infrastructure.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.nem.sdk.infrastructure.model.CommunicationTimestamps;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NodeTimeDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-24T01:47:49.709+02:00")
public class NodeTimeDTO {
  @SerializedName("communicationTimestamps")
  private CommunicationTimestamps communicationTimestamps = null;

  public NodeTimeDTO communicationTimestamps(CommunicationTimestamps communicationTimestamps) {
    this.communicationTimestamps = communicationTimestamps;
    return this;
  }

   /**
   * Get communicationTimestamps
   * @return communicationTimestamps
  **/
  @ApiModelProperty(required = true, value = "")
  public CommunicationTimestamps getCommunicationTimestamps() {
    return communicationTimestamps;
  }

  public void setCommunicationTimestamps(CommunicationTimestamps communicationTimestamps) {
    this.communicationTimestamps = communicationTimestamps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeTimeDTO nodeTimeDTO = (NodeTimeDTO) o;
    return Objects.equals(this.communicationTimestamps, nodeTimeDTO.communicationTimestamps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(communicationTimestamps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeTimeDTO {\n");
    
    sb.append("    communicationTimestamps: ").append(toIndentedString(communicationTimestamps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

